<a href="https://colab.research.google.com/github/Ahmethan96/Data_science/blob/main/Pytorch/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Creating tensors**

In [1]:
import torch

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
print(type(scalar))

<class 'torch.Tensor'>


In [4]:
scalar.ndim

0

In [5]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [6]:
print(type(scalar.item()))

<class 'int'>


In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape
# The above returns torch.Size([2]) which means our vector has a shape of [2]. This is because of the two elements we placed inside the square brackets ([7, 7]).

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
TENSOR2

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
TENSOR2.ndim

2

In [22]:
TENSOR2.shape

torch.Size([3, 3])

In [23]:
TENSOR3 = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [26]:
TENSOR3.ndim

3

In [24]:
TENSOR3.shape

torch.Size([1, 3, 3])

In [31]:
TENSOR3[0][1][0]

tensor(4)

In [33]:
TENSOR4 = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size= (3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.9866, 0.0907, 0.7739, 0.9663],
         [0.8214, 0.9086, 0.5946, 0.0925],
         [0.9677, 0.8457, 0.4456, 0.1245]]),
 torch.float32)

In [18]:
rand = torch.rand(size= (5, 5))
rand

tensor([[0.1638, 0.9577, 0.5838, 0.4688, 0.7068],
        [0.1043, 0.9147, 0.4696, 0.1723, 0.5430],
        [0.3539, 0.1913, 0.9692, 0.1702, 0.9132],
        [0.8360, 0.5702, 0.0371, 0.2113, 0.5999],
        [0.0487, 0.0340, 0.6268, 0.8575, 0.8562]])

In [19]:
rand.shape

torch.Size([5, 5])