<a href="https://colab.research.google.com/github/Ahmethan96/Data_science/blob/main/Pytorch/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Creating tensors**

In [1]:
import torch

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
print(type(scalar))

<class 'torch.Tensor'>


In [4]:
scalar.ndim

0

In [5]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [6]:
print(type(scalar.item()))

<class 'int'>


In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape
# The above returns torch.Size([2]) which means our vector has a shape of [2]. This is because of the two elements we placed inside the square brackets ([7, 7]).

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
m = torch.tensor([[1, 5, 0],[6, 7, 0]])
m

tensor([[1, 5, 0],
        [6, 7, 0]])

In [12]:
m.ndim

2

In [13]:
m.shape

torch.Size([2, 3])

In [14]:
m.dtype

torch.int64

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
MATRIX.dtype

torch.int64

In [18]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
TENSOR2

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
TENSOR2.ndim

2

In [23]:
TENSOR2.shape

torch.Size([3, 3])

In [24]:
TENSOR3 = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [25]:
TENSOR3.ndim

3

In [26]:
TENSOR3.shape

torch.Size([1, 3, 3])

In [27]:
TENSOR3[0][1][0]

tensor(4)

In [28]:
TENSOR4 = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR4

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [29]:
TENSOR5 = torch.tensor([[1], [2], [3]])
TENSOR5

tensor([[1],
        [2],
        [3]])

In [30]:
TENSOR5.shape

torch.Size([3, 1])

In [31]:
TENSOR5.ndim

2

In [32]:
TENSORS6 = torch.tensor([[[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]]])
TENSORS6

tensor([[[[[ 1,  2,  3],
           [ 4,  5,  6],
           [ 7,  8,  9],
           [10, 11, 12]]]]])

In [33]:
TENSORS6.ndim

5

In [34]:
TENSORS6.shape

torch.Size([1, 1, 1, 4, 3])

In [35]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size= (3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.2400, 0.0473, 0.6341, 0.4563],
         [0.5712, 0.7384, 0.3660, 0.0575],
         [0.9991, 0.5359, 0.3971, 0.7472]]),
 torch.float32)

In [36]:
rand = torch.rand(size= (5, 5))
rand

tensor([[0.9251, 0.0430, 0.8980, 0.3597, 0.7828],
        [0.7083, 0.5425, 0.4696, 0.3014, 0.2729],
        [0.6701, 0.8774, 0.6073, 0.0736, 0.1172],
        [0.3667, 0.2137, 0.6077, 0.5866, 0.0514],
        [0.9948, 0.9440, 0.3095, 0.4229, 0.0855]])

In [37]:
rand.shape

torch.Size([5, 5])

In [38]:
rand_image = torch.rand(size= (224, 224, 3))
rand_image

tensor([[[0.9608, 0.7601, 0.5012],
         [0.0901, 0.4662, 0.2736],
         [0.0242, 0.7735, 0.6557],
         ...,
         [0.3322, 0.9845, 0.0216],
         [0.1552, 0.8019, 0.8828],
         [0.6822, 0.2138, 0.2931]],

        [[0.8863, 0.9810, 0.0130],
         [0.1510, 0.7393, 0.6886],
         [0.4129, 0.4410, 0.7692],
         ...,
         [0.2036, 0.6548, 0.0747],
         [0.1962, 0.5329, 0.4851],
         [0.5893, 0.2062, 0.6151]],

        [[0.2297, 0.6941, 0.9300],
         [0.3023, 0.0050, 0.3393],
         [0.0980, 0.4203, 0.6199],
         ...,
         [0.4030, 0.7898, 0.7844],
         [0.0622, 0.6189, 0.2972],
         [0.1288, 0.1704, 0.5526]],

        ...,

        [[0.5359, 0.8380, 0.4182],
         [0.2685, 0.2256, 0.0913],
         [0.4052, 0.2855, 0.2775],
         ...,
         [0.5141, 0.3923, 0.9184],
         [0.2305, 0.4047, 0.9816],
         [0.7686, 0.0729, 0.3239]],

        [[0.0533, 0.4163, 0.3914],
         [0.8463, 0.7947, 0.8611],
         [0.

In [39]:
rand_image.ndim

3

In [45]:
rand_image1 = torch.rand(size= (3, 2, 5))
rand_image1

tensor([[[0.2934, 0.9472, 0.0221, 0.4635, 0.4982],
         [0.7446, 0.0126, 0.8874, 0.6273, 0.2540]],

        [[0.3959, 0.1422, 0.1548, 0.4473, 0.2542],
         [0.5049, 0.6011, 0.9278, 0.0943, 0.3965]],

        [[0.7331, 0.4164, 0.9588, 0.8734, 0.2068],
         [0.3417, 0.3155, 0.8068, 0.0986, 0.3121]]])

In [47]:
rand_image1.ndim

3

In [48]:
rand_image1.shape

torch.Size([3, 2, 5])

In [49]:
image = torch.rand(6, 5)
image

tensor([[0.9463, 0.4166, 0.4474, 0.3972, 0.2897],
        [0.6181, 0.2730, 0.9359, 0.5146, 0.5019],
        [0.2750, 0.9439, 0.4351, 0.3751, 0.7278],
        [0.4139, 0.8091, 0.7687, 0.4011, 0.2206],
        [0.6259, 0.1637, 0.6797, 0.2865, 0.7198],
        [0.3536, 0.0238, 0.2878, 0.6295, 0.0734]])

In [50]:
image.shape

torch.Size([6, 5])