<a href="https://colab.research.google.com/github/Ahmethan96/Data_science/blob/main/Pytorch/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Creating tensors**

In [1]:
import torch

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
print(type(scalar))

<class 'torch.Tensor'>


In [4]:
scalar.ndim

0

In [5]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [6]:
print(type(scalar.item()))

<class 'int'>


In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape
# The above returns torch.Size([2]) which means our vector has a shape of [2]. This is because of the two elements we placed inside the square brackets ([7, 7]).

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
m = torch.tensor([[1, 5, 0],[6, 7, 0]])
m

tensor([[1, 5, 0],
        [6, 7, 0]])

In [12]:
m.ndim

2

In [13]:
m.shape

torch.Size([2, 3])

In [14]:
m.dtype

torch.int64

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
MATRIX.dtype

torch.int64

In [18]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
TENSOR2

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
TENSOR2.ndim

2

In [23]:
TENSOR2.shape

torch.Size([3, 3])

In [24]:
TENSOR3 = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [25]:
TENSOR3.ndim

3

In [26]:
TENSOR3.shape

torch.Size([1, 3, 3])

In [27]:
TENSOR3[0][1][0]

tensor(4)

In [28]:
TENSOR4 = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR4

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [29]:
TENSOR5 = torch.tensor([[1], [2], [3]])
TENSOR5

tensor([[1],
        [2],
        [3]])

In [30]:
TENSOR5.shape

torch.Size([3, 1])

In [31]:
TENSOR5.ndim

2

In [32]:
TENSORS6 = torch.tensor([[[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]]])
TENSORS6

tensor([[[[[ 1,  2,  3],
           [ 4,  5,  6],
           [ 7,  8,  9],
           [10, 11, 12]]]]])

In [33]:
TENSORS6.ndim

5

In [34]:
TENSORS6.shape

torch.Size([1, 1, 1, 4, 3])

In [35]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size= (3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.2301, 0.3663, 0.4420, 0.7228],
         [0.7493, 0.2740, 0.9823, 0.9352],
         [0.4045, 0.4746, 0.3677, 0.9124]]),
 torch.float32)

In [36]:
rand = torch.rand(size= (5, 5))
rand

tensor([[0.2916, 0.8688, 0.7488, 0.1224, 0.7635],
        [0.5177, 0.3497, 0.9031, 0.5538, 0.0744],
        [0.1177, 0.1275, 0.3971, 0.1612, 0.6221],
        [0.8697, 0.9516, 0.6972, 0.4385, 0.8907],
        [0.4314, 0.4549, 0.3691, 0.3464, 0.4254]])

In [37]:
rand.shape

torch.Size([5, 5])

In [38]:
rand_image = torch.rand(size= (224, 224, 3))
rand_image

tensor([[[0.0140, 0.5394, 0.4919],
         [0.7151, 0.9981, 0.5409],
         [0.4871, 0.6034, 0.5388],
         ...,
         [0.2849, 0.9050, 0.2642],
         [0.5058, 0.9983, 0.5602],
         [0.4457, 0.1754, 0.9839]],

        [[0.4644, 0.3086, 0.5114],
         [0.6861, 0.5259, 0.6478],
         [0.1299, 0.7811, 0.9050],
         ...,
         [0.8307, 0.4417, 0.5305],
         [0.2971, 0.8924, 0.9052],
         [0.1545, 0.9574, 0.7749]],

        [[0.1964, 0.6396, 0.6048],
         [0.4454, 0.7125, 0.4916],
         [0.7896, 0.6937, 0.6902],
         ...,
         [0.5507, 0.1396, 0.1200],
         [0.1015, 0.9557, 0.0720],
         [0.8955, 0.4378, 0.9786]],

        ...,

        [[0.5778, 0.7484, 0.3870],
         [0.0558, 0.3416, 0.4283],
         [0.1864, 0.6748, 0.8232],
         ...,
         [0.9903, 0.8940, 0.6464],
         [0.9270, 0.3959, 0.0490],
         [0.9188, 0.3476, 0.7782]],

        [[0.5083, 0.5453, 0.2784],
         [0.5548, 0.1951, 0.8495],
         [0.

In [39]:
rand_image.ndim

3

In [40]:
rand_image1 = torch.rand(size= (3, 2, 5))
rand_image1

tensor([[[0.6616, 0.8120, 0.0676, 0.0926, 0.7967],
         [0.2216, 0.0948, 0.9244, 0.9821, 0.1659]],

        [[0.1650, 0.3052, 0.0311, 0.2827, 0.5741],
         [0.9795, 0.8757, 0.5013, 0.7227, 0.1112]],

        [[0.3475, 0.1562, 0.5509, 0.8208, 0.2681],
         [0.7067, 0.0050, 0.7558, 0.2392, 0.1533]]])

In [41]:
rand_image1.ndim

3

In [42]:
rand_image1.shape

torch.Size([3, 2, 5])

In [43]:
image = torch.rand(6, 5)
image

tensor([[0.6189, 0.2635, 0.1668, 0.9594, 0.5755],
        [0.5316, 0.1221, 0.3705, 0.2513, 0.0325],
        [0.4180, 0.0193, 0.0608, 0.8077, 0.5980],
        [0.9440, 0.4548, 0.1047, 0.6846, 0.1338],
        [0.1408, 0.1633, 0.4564, 0.9899, 0.7210],
        [0.6631, 0.0190, 0.8225, 0.4789, 0.3141]])

In [44]:
image.shape

torch.Size([6, 5])

In [50]:
test = torch.rand(size= (1, 4, 5))
test

tensor([[[0.9051, 0.0686, 0.1981, 0.3681, 0.0573],
         [0.9635, 0.7639, 0.1335, 0.2969, 0.1614],
         [0.1504, 0.2445, 0.8766, 0.4801, 0.7054],
         [0.4682, 0.3260, 0.3510, 0.7678, 0.0845]]])

In [52]:
# Create a tensor of all zeros
Zeros = torch.zeros(size = (5, 4))
Zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [53]:
# Create a tensor of all ones
Ones = torch.ones(4, 5)
Ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

**Creating a range and tensors like**

In [60]:
# torch.range
zero_to_ten = torch.range(0, 10)
zero_to_ten

<ipython-input-60-cd505cea6756>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten = torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [61]:
for i in range(10):
  print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 

In [62]:
# torch.arange
new_zero_to_ten = torch.arange(0, 10)
new_zero_to_ten


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
new_zero_to_ten[8]

tensor(8)

In [67]:
data_type = torch.rand(size = (5, 5), dtype= torch.float32)
data_type

tensor([[4.4405e-01, 8.2167e-01, 7.4654e-01, 9.6127e-01, 2.0949e-02],
        [8.6150e-01, 5.3541e-01, 5.7007e-01, 6.0195e-04, 9.5439e-01],
        [5.7502e-02, 8.3648e-01, 7.8434e-01, 7.8742e-01, 5.3277e-01],
        [8.2468e-01, 9.4720e-01, 1.1189e-01, 4.8132e-01, 9.8467e-01],
        [5.8219e-02, 7.4680e-01, 2.9353e-01, 3.8160e-01, 4.0748e-01]])

In [68]:
data_type.dtype

torch.float32

**Getting information from tensors**
Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

shape - what shape is the tensor? (some operations require specific shape rules)
dtype - what datatype are the elements within the tensor stored in?
device - what device is the tensor stored on? (usually GPU or CPU)

In [70]:
some_data = torch.rand(3, 4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_data.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.2376, 0.3891, 0.6301, 0.7972],
        [0.4310, 0.0327, 0.4304, 0.2400],
        [0.0347, 0.1360, 0.3203, 0.4903]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Note: When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where":

"what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where"

**basic operation**


In [71]:
# Create a tensor of values and add a number to it
add = torch.rand(size= (4, 5))
new = add + 10
new

tensor([[10.4715, 10.7255, 10.3047, 10.6696, 10.5735],
        [10.3694, 10.0427, 10.9369, 10.1339, 10.0659],
        [10.6852, 10.5874, 10.7367, 10.5096, 10.0758],
        [10.6793, 10.2937, 10.9269, 10.7741, 10.1551]])

In [74]:
mul = torch.rand(size = (4, 4))
mult = mul * 10
mult


tensor([[5.3784, 6.2352, 1.2953, 4.5097],
        [3.8999, 5.8255, 8.4137, 7.6375],
        [5.0033, 0.6661, 8.3310, 0.6019],
        [4.8399, 3.0271, 3.7664, 2.9585]])

In [76]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [77]:
print(tensor, "*", tensor)
print("equals", tensor * tensor)


tensor([1, 2, 3]) * tensor([1, 2, 3])
equals tensor([1, 4, 9])
