<a href="https://colab.research.google.com/github/Ahmethan96/Data_science/blob/main/Pytorch/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Creating tensors**

In [1]:
import torch

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
print(type(scalar))

<class 'torch.Tensor'>


In [4]:
scalar.ndim

0

In [5]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [6]:
print(type(scalar.item()))

<class 'int'>


In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape
# The above returns torch.Size([2]) which means our vector has a shape of [2]. This is because of the two elements we placed inside the square brackets ([7, 7]).

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [30]:
m = torch.tensor([[1, 5, 0],[6, 7, 0]])
m

tensor([[1, 5, 0],
        [6, 7, 0]])

In [31]:
m.ndim

2

In [32]:
m.shape

torch.Size([2, 3])

In [33]:
m.dtype

torch.int64

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [34]:
MATRIX.dtype

torch.int64

In [13]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
TENSOR2

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR2.ndim

2

In [18]:
TENSOR2.shape

torch.Size([3, 3])

In [19]:
TENSOR3 = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [20]:
TENSOR3.ndim

3

In [21]:
TENSOR3.shape

torch.Size([1, 3, 3])

In [22]:
TENSOR3[0][1][0]

tensor(4)

In [47]:
TENSOR4 = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR4

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [46]:
TENSOR5 = torch.tensor([[1], [2], [3]])
TENSOR5

tensor([[1],
        [2],
        [3]])

In [44]:
TENSOR5.shape

torch.Size([3, 1])

In [42]:
TENSOR5.ndim

1

In [61]:
TENSORS6 = torch.tensor([[[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]]])
TENSORS6

tensor([[[[[ 1,  2,  3],
           [ 4,  5,  6],
           [ 7,  8,  9],
           [10, 11, 12]]]]])

In [62]:
TENSORS6.ndim

5

In [63]:
TENSORS6.shape

torch.Size([1, 1, 1, 4, 3])

In [24]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size= (3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.5116, 0.4960, 0.6492, 0.0719],
         [0.0552, 0.1862, 0.9686, 0.6151],
         [0.0123, 0.1654, 0.1250, 0.4551]]),
 torch.float32)

In [25]:
rand = torch.rand(size= (5, 5))
rand

tensor([[0.3013, 0.7791, 0.5472, 0.8161, 0.1264],
        [0.6197, 0.7000, 0.4762, 0.8136, 0.5768],
        [0.6713, 0.8534, 0.4695, 0.0860, 0.8456],
        [0.2784, 0.8572, 0.2999, 0.3140, 0.7565],
        [0.8256, 0.6279, 0.2886, 0.1616, 0.8824]])

In [26]:
rand.shape

torch.Size([5, 5])

In [68]:
rand_image = torch.rand(size= (224, 224, 3))
rand_image

tensor([[[0.9110, 0.8959, 0.0792],
         [0.4127, 0.3574, 0.1950],
         [0.5968, 0.0773, 0.2748],
         ...,
         [0.8226, 0.4444, 0.4586],
         [0.2115, 0.3717, 0.3019],
         [0.2666, 0.2028, 0.2203]],

        [[0.5565, 0.9595, 0.6815],
         [0.9139, 0.4757, 0.5233],
         [0.0067, 0.7307, 0.5736],
         ...,
         [0.4767, 0.7236, 0.8247],
         [0.1038, 0.0885, 0.3622],
         [0.5665, 0.0947, 0.5261]],

        [[0.6135, 0.9186, 0.7951],
         [0.9481, 0.5535, 0.0779],
         [0.0954, 0.9707, 0.7142],
         ...,
         [0.6038, 0.5471, 0.1755],
         [0.3688, 0.0682, 0.4121],
         [0.3300, 0.5941, 0.4355]],

        ...,

        [[0.7949, 0.2037, 0.3059],
         [0.3441, 0.8018, 0.4546],
         [0.9264, 0.8825, 0.8927],
         ...,
         [0.2411, 0.1818, 0.2303],
         [0.4197, 0.0533, 0.5356],
         [0.4778, 0.8412, 0.2372]],

        [[0.8819, 0.5588, 0.4388],
         [0.6623, 0.5921, 0.5542],
         [0.

In [71]:
rand_image.ndim

3