In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



In [ ]:
print(torch.__version__)

2.0.1+cu118


### **Introduction to Tensors**


## Creating tensors

PyTorch.Tensor are created by using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
print(type(scalar))

<class 'torch.Tensor'>


In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
scalar.ndim

0

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
z = scalar.item()
z
print(type(z))

<class 'int'>


In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector
print(type(vector))

<class 'torch.Tensor'>


In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX
MATRIX.ndim


2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
IBO = torch.tensor([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
IBO

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
IBO.shape



torch.Size([3, 3])

In [ ]:
IBRAHIM = torch.tensor([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]])

IBRAHIM

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [ ]:
IBRAHIM.shape

torch.Size([3, 4])

### Random tensors

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8478, 0.2265, 0.0830, 0.8500],
        [0.6438, 0.5079, 0.9242, 0.2314],
        [0.8144, 0.2805, 0.7958, 0.0796]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size= (224, 224, 3)) # height, width, clolour channels
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
random_image_size_tensor.ndim

3

### Zeros and ones

In [ ]:
zeros = torch.zeros(size= (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Creating a range of tensors and tensor-like

In [ ]:
one_to_ten = torch.arange(start= 1, end= 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten.ndim

1

In [ ]:
one_to_ten.shape

torch.Size([10])


### Tensor datatypes

# Note: Tensor datatypes is one of the 3 big errors you will run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype= None,
                                                device= None,
                                                requires_grad= False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1880, 0.4670, 0.1351, 0.1434],
        [0.1307, 0.1252, 0.8474, 0.3141],
        [0.4416, 0.1136, 0.4134, 0.9061]])

In [ ]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# **Manipulating Tensors (tensor operations)**

## Tensor operatinos include:


*   Addition
*   Subtraction
*   Multiplication (element-wise)
*   Division
*   Matrix multiplication




In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

### **Matrix multiplication**

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

https://www.mathsisfun.com/algebra/matrix-multiplying.html




In [ ]:
# Element-wise multipliation
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A, tensor_B) ## you will get the following error
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

RuntimeError: ignored

In [ ]:
# To fix the above error
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_B.shape, tensor_B.T.shape

In [ ]:
torch.matmul(tensor_A, tensor_B.T) # Error solved

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# **Tensor aggregation**
## Finding the min, max, sum, etc

In [ ]:
# Create a tensor
x =  torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on the top of each other (vstack) or side
by side (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a
certain way




In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x.dtype

torch.float32

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Stack tensors on the top ofeach other
x_stacked = torch.stack([x, x, x, x], dim= 0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Stack tensors on the top ofeach other
x_stacked = torch.stack([x, x, x, x], dim= 1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimension from a target tensor

x_reshaped



tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# torch.permute - rearrange the dimenison of a target tensor in a specific order
x_original = torch.rand(size= (224, 244, 3)) # [height, width, coulour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour channels, height, width]

Previous shape: torch.Size([224, 244, 3])
New shape: torch.Size([3, 224, 244])


## **Indexing (selecting data from tensors)**



In [ ]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][1]

tensor([4, 5, 6])

In [ ]:
x[0][1][2]

tensor(6)

In [ ]:
x.dtype

torch.int64

In [ ]:
# Get all values of the 0th and 1st dimesnion but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

## **Reproducbility (trying to take random out of random)**

In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again ....

In [ ]:
import torch
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4753, 0.2371, 0.1815, 0.9288],
        [0.2918, 0.1360, 0.9275, 0.8472],
        [0.0312, 0.6627, 0.1915, 0.6515]])
tensor([[0.4922, 0.5007, 0.7760, 0.3017],
        [0.8024, 0.5485, 0.3161, 0.1824],
        [0.5722, 0.4215, 0.7084, 0.9813]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computation)
GPUs = faster computation on numbers, thank to CUDA + NVIDIA + PyTorch working behinde the scenes to make everything good

###  **1. Getting a GPU**
1. Easiest - use Google Colab for a free GPU (option to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the invesment of purchas (https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/)
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documents:

In [1]:
!nvidia-smi


Fri Jun 16 13:58:40 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### **2. Check for GPU access with PyTorch**

In [3]:
import torch

torch.cuda.is_available()

True

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

device

'cuda'

In [6]:
# Count number of devices
torch.cuda.device_count()

1

### **Putting tensors (and models) on the GPU**

The reason we want our tensors/models on the GPU is because a GPU results in faster computation

In [7]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### **4. Moving tensors back to the CPU**